//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVENTMGT_SYSTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRegistration
    {
        public int uuid { get; set; }
        public Nullable<int> enentId { get; set; }
        public Nullable<int> attendee { get; set; }
    
        public virtual Attendee Attendee1 { get; set; }
        public virtual EventDetail EventDetail { get; set; }
    }
}
