//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EVENTMGT_SYSTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventDetail()
        {
            this.EventRegistrations = new HashSet<EventRegistration>();
        }
    
        public int uuid { get; set; }
        public string eventName { get; set; }
        public string eventDescription { get; set; }
        public Nullable<int> venue { get; set; }
        public Nullable<System.DateTime> eventDate { get; set; }
        public string eventTime { get; set; }
        public Nullable<int> eventType { get; set; }
    
        public virtual EventType EventType1 { get; set; }
        public virtual Venue Venue1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventRegistration> EventRegistrations { get; set; }
    }
}
